apiVersion: v1
kind: ServiceAccount
metadata:
  name: phase3-sa
  namespace: phase3
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: phase3-role
  namespace: phase3
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: phase3-rolebinding
  namespace: phase3
subjects:
  - kind: ServiceAccount
    name: phase3-sa
    namespace: phase3
roleRef:
  kind: Role
  name: phase3-role
  apiGroup: rbac.authorization.k8s.io
