{{- if .Values.networkPolicy.enabled -}}
apiVersion: {{ include "todo-app.networkPolicy.apiVersion" . }}
kind: NetworkPolicy
metadata:
  name: {{ include "todo-app.fullname" . }}-network-policy
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
spec:
  podSelector: {}
  policyTypes:
    {{- toYaml .Values.networkPolicy.policyTypes | nindent 4 }}
  ingress:
    {{- toYaml .Values.networkPolicy.ingress | nindent 4 }}
  egress:
    {{- toYaml .Values.networkPolicy.egress | nindent 4 }}
{{- end }}
